name: Build and Test

on:
  push:
    branches: ["main"]
    paths:
      - src/**/*
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: ["main"]
    paths:
      - src/**/*
      - Cargo.toml
      - Cargo.lock
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install clippy
        run: rustup component add clippy
      - name: Run linter
        run: cargo clippy --verbose
      - name: Dry publish
        run: cargo publish --dry-run
