name: Publish
on:
  workflow_run:
    workflows:
      - "Build and Test"
    types:
      - completed
    branches:
      - main
env:
  CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout files"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: "Install cargo-release"
        run: cargo install cargo-release

      - name: "Configure Git"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Release and Publish"
        run: cargo release patch --execute --no-confirm --no-verify # --no-verify skips dirty checks
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
